### ISSUE TITLE
Add support for delay in GTween

### ISSUE THREAD

**Issue by TinyMatt** [Guillemsc/GTweens#4]
IMHO it could be quite useful to be able to set a start delay in GTween (without using the Sequence builder). 

The current syntax would really benefit from such a change. Eg with godot extensions you could simply do a `TweenPosition` and call `.SetDelay` on it to offset the Tick by a certain time, keeping the code simple and easy to follow. 

Is there a reason why it wasn't implemented in the first place? Maybe I'm missing something.

**Comment by Guillemsc** [comment]
My thought process was that: if you need delays, it's because you are building a complex sequence. In retrospect, this is not necessarily true, and as you said, a simple SetDelay could be beneficial.

**Comment by Guillemsc** [comment]
Added a `SetDelay` method to the `GTween` class. It will be available in the next version! :)
